.\" audiotool - manipulate telephonic audio files
.\" Copyright (c) 2005-2011 David Sugar, Tycho Softworks
.\"
.\" This manual page is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" This manual page is written especially for Debian GNU/Linux.
.\"
.TH audiotool "1" "October 2004" "GNU Bayonne Audio Tool" "GNU Telephony"
.SH NAME
audiotool \- manipulate telephonic audio files.
.SH SYNOPSIS
.B audiotool
.RI [ options ]
.B command
.RI [ arguments... ]
.SH DESCRIPTION
Audiotool is used to copy, manipulate, and examine the contents of audio
files.  These audio files may be raw headerless audio data or audio stored in
common data files such as .wav or .au files.  In the near future
audiotool will also support packetized audio files such as .mp3 and .ogg.
.PP
.SH OPTIONS
.TP
.BI -encoding= pcmu
Specify audio encoding format.
.TP
.BI -framing= 20ms
Specify audio framing size.
.SH COMMANDS
.TP
.B append
appends the content of other audio files into an existing audio file.
The offset to save within the existing file may be specified.
If nessisary the content of the specified files will be re-encoded in
the codec of the file being appended to.
.TP
.B build
Build a brand new audio file from scratch and then copy content from
existing audio files into it.  The encoding of the new
audio file will either be based on the file extension, the audio file
that is being copied into it, or by specifying the encoding format
directly.
.TP
.B chart
This is used to generate an energy chart profile of the audio file frame
by frame.  A * indicates solid audio content, a ^ indicates what might
be a lead or trailer section of partial content, and a . indicates
relative silence.  Soon a autotrim option will be added to audiotool to
remove silent frames.
.TP
.B codecs
List all active codec objects.  If you have plugins which are loaded that
creates codec objects which match a built-in codec, the plugin will be
selected first.
.TP
.B info
The info command gives you basic information on the audio file,
including what format it is stored as, what codec the audio data is
encoded in, how much data is in the file, what the bit rate used is,
etc.
.TP
.B notation
Notation can be used to either set or display the annotation stored in
audio files which support annotations, such as .au and .wav files.
.TP
.B play
Plays the content of the audio file to the default system audio device
(soundcard).  Play is supported on w32 and posix systems that support
oss audio.  Future work will expand to additional platforms.
.TP
.B plugins
This simply returns the path to the plugins directory.  All plugins are
loaded with Audio::init().  Plugins are not supported when building with
static linkage.
.TP
.B strip
Strips out all silent frames from an audio file.  Silent frames are
those which fall below a threshold and that have no peak impulse above
the threshold.
.TP
.B trim
Removes leading and trailing "silence" from a file.  The -padding option
may be used to add additional silent frames at the end of the file after
it has been trimmed, as this may be needed for files that will later be
used to join together phrases.
.SH BUGS
At this time audiotool does not perform sample rate conversion.  Appending
and building from files which are encoded at different sample rates could
have amusing results.
.SH AUTHOR
Written by David Sugar.
.SH "REPORTING BUGS"
Report bugs to <dyfet@gnu.org>.
.SH COPYRIGHT
Copyright \(co 2005-2011 David Sugar, Tycho Softworks
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
