.TH phrasebook "1" "December 2010" "GNU Bayonne Phrasebook" "GNU Telephony"
.SH NAME
baylint \- verify bayonne script file
.SH SYNOPSIS
.B baylint
.I [options...]
.BR scriptfile
.SH DESCRIPTION
This provides a ``lint'' command for the Bayonne scripting language.
.PP
.SH OPTIONS
.TP
.BI -driver= name
Specify server driver name for lint definitions.
.TP
.BI -modules= list
Specify list of modules for additional definitions.
.SH AUTHOR
Written by David Sugar.
.SH "REPORTING BUGS"
Report bugs to <dyfet@gnu.org>.
.SH COPYRIGHT
Copyright \(co 2010 David Sugar, Tycho Softworks
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
