.\" phrasebook - process phrasebook rules
.\" Copyright (c) 2010-2011 David Sugar, Tycho Softworks
.\"
.\" This manual page is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" This manual page is written especially for Debian GNU/Linux.
.\"
.TH phrasebook "1" "December 2010" "GNU Bayonne Phrasebook" "GNU Telephony"
.SH NAME
phrasebook \- process phrasebook rules
.SH SYNOPSIS
.B phrasebook
.RI [ options ]
.BR command
.I phrase...
.SH DESCRIPTION
Phrasebook manipulates names and lists of audio files that would be assembled
to speak phrases based on Phrasebook translation rules.  Phrasebook can also
"speak" a rule.  Phrases include text, numbers, and format modifiers, all of
which may be spoken by assembling correct pre-recorded audio samples.
.PP
.SH OPTIONS
.TP
.BI -lang= C
Specify language to use.
.SH COMMANDS
.TP
.B display
shows list of audio prompts that would be spoken in the selected language
for a given phrase.
.TP
.B paths
shows actual file paths for audio prompts that would be spoken in the selected
language for a given phrase.
.TP
.B speak
outputs the audio of a given phrase to the current default audio device.
.SH AUTHOR
Written by David Sugar.
.SH "REPORTING BUGS"
Report bugs to <dyfet@gnu.org>.
.SH COPYRIGHT
Copyright \(co 2010-2011 David Sugar, Tycho Softworks
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
