.\" tonetool - create and manipulate telephony tones.
.\" Copyright (c) 2005-2011 David Sugar, Tycho Softworks
.\"
.\" This manual page is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" This manual page is written especially for Debian GNU/Linux.
.\"
.TH tonetool "1" "Febuary 2005" "GNU Bayonne Tone Tool" "GNU Telephony"
.SH NAME
tonetool \- create and manipulate telephony tones.
.SH SYNOPSIS
.B tonetool
.I [options...]
.B command
.IR [arguments...]
.SH DESCRIPTION
Teltones is used to generate or play audio telephony tones based on a
"spec".  The spec can be "dtmf digitstring" to create or play dtmf digits,
"mf digitstring" to create or play mf digits, "single ...", to create or
play a single tone, or "dual ..." to create or play a dual tone.
Teltones can also be used to detect dtmf digits contained in audio files.
.PP
.SH OPTIONS
.TP
.BI -encoding= pcmu
Specify audio encoding format.
.TP
.BI -framing= 20ms
Specify audio framing size.
.TP
.BI -interdigit= 60ms
Specify dtmf interdigit time.
.TP
.BI -level= 30000
Specify base audio level to use.
.SH COMMANDS
.TP
.B append
Appends the generated tone to the end of an existing audio file.
.TP
.B create
Create a new audio file from scratch and fill with the tone specified.
.TP
.B detect
Process an existing audio file and report on dtmf digits found.
.TP
.B list
List a tone entry definition by sequencing.
.B play
Generate a tone or dialing string and play it to the local soundcard.
.SH BUGS
At this time tonetool always assumes all data is sourced at 8khz and
does not support sample rate conversion.
.SH AUTHOR
Written by David Sugar.
.SH "REPORTING BUGS"
Report bugs to <dyfet@gnu.org>.
.SH COPYRIGHT
Copyright \(co 2005-2011 David Sugar, Tycho Softworks.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
